In [1]:
from trees import *
from treePlotter import *
import numpy as np
import pandas as pd

raw_train=pd.read_excel('HW3 - Test data set 1.xlsx',index_col=0)

dataset=np.array(raw_train,dtype=str).tolist()

label=np.array(raw_train.T.index,dtype=str)[:-1].tolist()

obj=np.array(raw_train.T.index,dtype=str)[-1]

In [2]:
myTree=createTree(dataset,label)

0.833333333333
0.166666666667
Talent High 0.650022421648
0.5
0.5
Talent Medium 1.0
0.375
0.625
Talent Low 0.954434002925
feature for  Talent 0.876780327664

0.375
0.625
AveHeight NBA_tall 0.954434002925
1.0
AveHeight NBA_medium 0.0
0.428571428571
0.571428571429
AveHeight NBA_short 0.985228136034
feature for  AveHeight 0.726603448782

0.75
0.25
GreatCoach Yes 0.811278124459
0.25
0.75
GreatCoach No 0.811278124459
feature for  GreatCoach 0.811278124459

0.7
0.3
TeamChemistry Great 0.881290899231
0.4
0.6
TeamChemistry Okay 0.970950594455
feature for  TeamChemistry 0.926120746843

In [ ]:
createPlot(myTree)

In [12]:
pd.read_excel('HW3 - Test data set 1.xlsx')

     #  Talent   AveHeight GreatCoach TeamChemistry WinTitle?
0    1     Low  NBA_medium        Yes         Great       Yes
1    2     Low   NBA_short        Yes         Great       Yes
2    3  Medium   NBA_short        Yes          Okay        No
3    4  Medium    NBA_tall        Yes         Great       Yes
4    5     Low   NBA_short         No          Okay        No
5    6    High   NBA_short        Yes         Great       Yes
6    7     Low    NBA_tall        Yes         Great        No
7    8     Low  NBA_medium        Yes          Okay       Yes
8    9     Low    NBA_tall         No          Okay        No
9   10  Medium    NBA_tall        Yes          Okay       Yes
10  11     Low   NBA_short        Yes          Okay        No
11  12    High    NBA_tall         No          Okay        No
12  13  Medium  NBA_medium        Yes         Great       Yes
13  14  Medium    NBA_tall         No         Great        No
14  15    High    NBA_tall        Yes         Great       Yes
15  16  Medium   NBA_short         No          Okay        No
16  17    High  NBA_medium         No          Okay       Yes
17  18    High   NBA_short        Yes         Great       Yes
18  19    High  NBA_medium         No          Okay       Yes
19  20     Low    NBA_tall         No         Great        No